name: qmk_setup

on:
  push:
    # branches: main

jobs:
  qmk_setup:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Generate date as version
        run: echo $(date "+%D")
        id: version
      - 
        name: add qmk deb repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb https://linux.qmk.fm/ focal main
          repo-name: qmk
          keys-asc: https://linux.qmk.fm/gpg_pubkey.txt
      # - 
      #   name: Check out QMK firmware
      #   uses: actions/checkout@master
      #   with:
      #     repository: qmk/qmk_firmware 
      -
        name: Install QMK toolchain
        run: |
          sudo apt update
          sudo apt install qmk
          qmk setup -y
      -
        name: Checkout own repo
        uses: actions/checkout@v2
      -
        name: Copy repo keymap
        run: |
          mkdir -p /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.h /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.c /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.mk /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
      -
        name: Compile firmware
        run: |
          qmk compile -j 0 -kb splitkb/kyria -km 4542elgh
      # - 
      #   name: Uploading artifacts # This have a 90 day data retention policy, for longer retention period, use releases
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Kyria binary
      #     path: |
      #       /home/runner/qmk_firmware/.build/*.hex
      - 
        name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - 
        name: Upload hex artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /home/runner/qmk_firmware/.build/
          asset_name: splitkb_kyria_rev1_4542elgh.hex
          asset_content_type: application/octet-stream
