name: qmk_setup

on:
  # Always run actions when pushed, might want to trigger only on main when deploying
  push:
    # branches: main

jobs:
  qmk_setup:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Generate date as version
        # Make sure to use the set-output prefix so you can access this output in other steps
        run: echo "::set-output name=dateVer::"$(date "+%D")
        id: version
      - 
        name: Get short SHA
        id: shortSHA
        # Make sure to use the set-output prefix so you can access this output in other steps
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - 
        name: add qmk deb repository
        uses: myci-actions/add-deb-repo@10
        with:
          repo: deb https://linux.qmk.fm/ focal main
          repo-name: qmk
          keys-asc: https://linux.qmk.fm/gpg_pubkey.txt
      -
        name: Install QMK toolchain
        run: |
          sudo apt update
          sudo apt install qmk
          qmk setup -y
      -
        # Check out the repo where this action lives
        name: Checkout own repo
        uses: actions/checkout@v2
      -
        # This is hardcoded for now, should be running with a config file
        name: Copy repo keymap
        run: |
          mkdir -p /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.h /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.c /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
          mv  /home/runner/work/QMK_Test/QMK_Test/*.mk /home/runner/qmk_firmware/keyboards/splitkb/kyria/keymaps/4542elgh
      -
        name: Compile firmware
        run: |
          qmk compile -j 0 -kb splitkb/kyria -km 4542elgh
      # - 
      #   name: Uploading artifacts # This have a 90 day data retention policy, for longer retention period, use releases
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Kyria binary
      #     path: |
      #       /home/runner/qmk_firmware/.build/*.hex
      - 
        name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.dateVer }} - ${{ steps.shortSHA.outputs.sha7 }}
          # This key should be unique each time new code is pushed, using commit hash
          tag_name: ${{ steps.shortSHA.outputs.sha7 }}
      - 
        name: Upload hex artifact to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          # Do not change
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          # Path is pointing to a file, not sure why but this works
          asset_path: /home/runner/qmk_firmware/.build/splitkb_kyria_rev1_4542elgh.hex
          asset_name: splitkb_kyria_rev1_4542elgh.hex
          # Refer to the correct MIME type. .bin .hex all use octet stream
          asset_content_type: application/octet-stream
